### ISSUE TITLE
Unexpected breaking change on patch version

### ISSUE THREAD

**Issue by foray1010** [JounQin/remark-preset-prettier#90]
Hi, I think this commit should be a breaking change on node version and should pump to v2 instead? https://github.com/JounQin/remark-preset-prettier/commit/1895900b45826d92b8373bf52c4022118be6ce87

**Comment by JounQin** [comment]
I'm sorry I didn't notice this issue previously.

```diff
  "engines": {
-     "node": ">=12.20"
+     "node": "^12.20 || ^14.18.0 || >=16.0.0"
   },
```

Mostly it should not be a breaking, but of course it could be.

Do you meet such situation?

**Comment by foray1010** [comment]
Yes, unfortunately I do. The reason is my libraries supports node 14.17, which is still within LTS range. Because of that, I have to test my libraries in node 14.17 and that is where I would hit this change.

**Comment by JounQin** [comment]
Sorry, I didn't mean to break your pipeline, I'll revert and publish a major version instead.

**Comment by JounQin** [comment]
@foray1010 `v1.0.2` has been released, I learned that my work could affect users unexpectedly now! I'll be more carefully in the future.
